Repository AppCenter-Snaptime/snaptime-springboot, pull requests merged in 2024-07, with the labels that each got.

#80 [Refactor] 스웨거에 스키마정보가 뜨도록 변경
  src/main/java/me/snaptime/snap/controller/SnapPagingController.java
  src/main/java/me/snaptime/social/controller/FriendShipController.java
  src/main/java/me/snaptime/social/controller/ReplyController.java
  src/main/java/me/snaptime/social/controller/SnapLikeController.java
Labels: 🎨Fix

#78 [Feat/Fix] userTagSnap메서드 추가 userUpdate 수정
  src/main/java/me/snaptime/common/exception/customs/ExceptionCode.java
  src/main/java/me/snaptime/user/controller/UserController.java
  src/main/java/me/snaptime/user/data/dto/response/userprofile/ProfileTagSnapResDto.java
  src/main/java/me/snaptime/user/data/repository/UserCustomRepository.java
  src/main/java/me/snaptime/user/data/repository/UserRepository.java
  src/main/java/me/snaptime/user/data/repository/impl/UserCustomRepositoryImpl.java
  src/main/java/me/snaptime/user/service/UserService.java
Labels: ✨ New Feature, 🎨Fix

#83 [Refactor] Snap 저장 로직을 개선합니다.
  src/main/java/me/snaptime/common/exception/customs/ExceptionCode.java
  src/main/java/me/snaptime/snap/component/crawling/CrawlingComponent.java
  src/main/java/me/snaptime/snap/component/crawling/CrawlingComponentImpl.java
  src/main/java/me/snaptime/snap/component/crawling/provider/HaruFilm.java
  src/main/java/me/snaptime/snap/component/crawling/provider/Provider.java
  src/main/java/me/snaptime/snap/component/encryption/EncryptionComponent.java
  src/main/java/me/snaptime/snap/component/encryption/EncryptionImpl.java
  src/main/java/me/snaptime/snap/component/file/FileComponent.java
  src/main/java/me/snaptime/snap/component/file/FileComponentImpl.java
  src/main/java/me/snaptime/snap/controller/SnapController.java
  src/main/java/me/snaptime/snap/service/AlbumService.java
  src/main/java/me/snaptime/snap/service/SnapService.java
  src/main/java/me/snaptime/snap/service/impl/AlbumServiceImpl.java
  src/main/java/me/snaptime/snap/service/impl/SnapServiceImpl.java
  src/main/java/me/snaptime/snap/util/ConnectionAction.java
  src/main/java/me/snaptime/snap/util/JsoupAction.java
  src/main/java/me/snaptime/social/service/SnapTagService.java
  src/test/java/me/snaptime/snap/service/SnapServiceImplTest.java
Labels: 🎨Fix

#85 [Fix] 태그 snap 조회 수정
  src/main/java/me/snaptime/user/controller/UserController.java
Labels: 🎨Fix

#103 [Feat] PhotoSignature 공급자 추가
  src/main/java/me/snaptime/crawling/controller/CrawlingController.java
  src/main/java/me/snaptime/crawling/service/provider/PhotoSignature.java
  src/main/java/me/snaptime/snap/controller/SnapController.java
  src/main/java/me/snaptime/util/ConnectionAction.java
  src/main/java/me/snaptime/util/JsoupAction.java
Labels: ✨ New Feature

#108 [Refactor] checkIsFollow메소드의 접근제어자를 public로 변경
  src/main/java/me/snaptime/friend/service/FriendService.java
  src/main/java/me/snaptime/friend/service/impl/FriendServiceImpl.java
Labels: 🎨Fix

#106 [Fix] url 수정, userUpdate http 메서드 변경
  src/main/java/me/snaptime/profile/controller/ProfileController.java
  src/main/java/me/snaptime/profile/dto/res/UserProfileResDto.java
  src/main/java/me/snaptime/profile/service/ProfileService.java
  src/main/java/me/snaptime/profile/service/impl/ProfileServiceImpl.java
  src/main/java/me/snaptime/profilePhoto/controller/ProfilePhotoController.java
  src/main/java/me/snaptime/user/controller/UserController.java
  src/main/java/me/snaptime/user/dto/req/UserUpdateReqDto.java
  src/main/java/me/snaptime/user/service/UserService.java
  src/main/java/me/snaptime/user/service/impl/UserServiceImpl.java
  src/test/java/me/snaptime/user/controller/UserControllerTest.java
  src/test/java/me/snaptime/user/service/UserServiceTest.java
Labels: 🎨Fix

#109 [Fix] url 컴포넌트 profilephoto 경로 수정, repsitory 경로 수정
  src/main/java/me/snaptime/component/url/UrlComponentImpl.java
  src/main/java/me/snaptime/config/SecurityConfig.java
  src/main/java/me/snaptime/profile/repository/ProfileRepository.java
  src/main/java/me/snaptime/profile/repository/impl/ProfileRepositoryImpl.java
  src/main/java/me/snaptime/profile/service/impl/ProfileServiceImpl.java
  src/main/java/me/snaptime/user/repository/UserCustomRepository.java
  src/main/java/me/snaptime/user/repository/UserRepository.java
Labels: 🎨Fix

#112 [Feat] Snap을 비공개로 전환시에 태그가 삭제되도록 함
  src/main/java/me/snaptime/snap/service/impl/SnapServiceImpl.java
Labels: ✨ New Feature

#111 [Refactor,Feat] convention 맞추기, RefreshToken 추가
  build.gradle
  src/main/generated/me/snaptime/profilePhoto/domain/QProfilePhoto.java
  src/main/generated/me/snaptime/user/domain/QUser.java
  src/main/java/me/snaptime/album/service/impl/AlbumServiceImpl.java
  src/main/java/me/snaptime/exception/ExceptionCode.java
  src/main/java/me/snaptime/friend/repository/impl/FriendPagingRepositoryImpl.java
  src/main/java/me/snaptime/friend/service/impl/FriendServiceImpl.java
  src/main/java/me/snaptime/jwt/JwtProvider.java
  src/main/java/me/snaptime/profile/controller/ProfileController.java
  src/main/java/me/snaptime/profile/dto/res/UserProfileResDto.java
  src/main/java/me/snaptime/profile/repository/ProfileRepository.java
  src/main/java/me/snaptime/profile/repository/impl/ProfileRepositoryImpl.java
  src/main/java/me/snaptime/profile/service/ProfileService.java
  src/main/java/me/snaptime/profile/service/impl/ProfileServiceImpl.java
  src/main/java/me/snaptime/profilePhoto/controller/ProfilePhotoController.java
  src/main/java/me/snaptime/profilePhoto/domain/ProfilePhoto.java
  src/main/java/me/snaptime/profilePhoto/dto/res/ProfilePhotoResDto.java
  src/main/java/me/snaptime/profilePhoto/repository/ProfilePhotoRepository.java
  src/main/java/me/snaptime/profilePhoto/service/impl/ProfilePhotoServiceImpl.java
  src/main/java/me/snaptime/redis/RedisConfig.java
  src/main/java/me/snaptime/redis/RefreshToken.java
  src/main/java/me/snaptime/redis/RefreshTokenRepository.java
  src/main/java/me/snaptime/reply/repository/impl/ChildReplyPagingRepositoryImpl.java
  src/main/java/me/snaptime/reply/repository/impl/ParentReplyPagingRepositoryImpl.java
  src/main/java/me/snaptime/reply/service/impl/ReplyServiceImpl.java
  src/main/java/me/snaptime/snap/repository/impl/SnapPagingRepositoryImpl.java
  src/main/java/me/snaptime/snap/service/impl/SnapPagingServiceImpl.java
  src/main/java/me/snaptime/snap/service/impl/SnapServiceImpl.java
  src/main/java/me/snaptime/user/controller/UserController.java
  src/main/java/me/snaptime/user/domain/User.java
  src/main/java/me/snaptime/user/dto/res/SignInResDto.java
  src/main/java/me/snaptime/user/dto/res/UserResDto.java
  src/main/java/me/snaptime/user/service/SignService.java
  src/main/java/me/snaptime/user/service/UserService.java
  src/main/java/me/snaptime/user/service/impl/SignServiceImpl.java
  src/main/java/me/snaptime/user/service/impl/UserServiceImpl.java
  src/test/java/me/snaptime/snap/controller/SnapPagingControllerTest.java
  src/test/java/me/snaptime/snap/service/SnapPagingServiceImplTest.java
  src/test/java/me/snaptime/social/controller/FriendControllerTest.java
  src/test/java/me/snaptime/social/controller/ReplyControllerTest.java
  src/test/java/me/snaptime/social/service/FriendServiceImplTest.java
  src/test/java/me/snaptime/user/controller/UserControllerTest.java
  src/test/java/me/snaptime/user/service/ProfilePhotoServiceTest.java
  src/test/java/me/snaptime/user/service/UserServiceTest.java
Labels: ✨ New Feature

#120 [Feat] 미확인 알림개수조회 기능구현 & 나에게 온 알림리스트 조회기능 구현
  src/main/java/me/snaptime/alarm/controller/AlarmController.java
  src/main/java/me/snaptime/alarm/domain/ReplyAlarm.java
  src/main/java/me/snaptime/alarm/dto/res/AlarmInfo.java
  src/main/java/me/snaptime/alarm/dto/res/FindAlarmsDto.java
  src/main/java/me/snaptime/alarm/repository/FollowAlarmRepository.java
  src/main/java/me/snaptime/alarm/repository/ReplyAlarmRepository.java
  src/main/java/me/snaptime/alarm/repository/SnapAlarmRepository.java
  src/main/java/me/snaptime/alarm/service/AlarmService.java
  src/main/java/me/snaptime/alarm/service/CreateAlarmService.java
  src/main/java/me/snaptime/alarm/service/impl/AlarmServiceImpl.java
  src/main/java/me/snaptime/alarm/service/impl/CreateAlarmServiceImpl.java
  src/main/java/me/snaptime/album/dto/res/FindAlbumResDto.java
  src/main/java/me/snaptime/album/service/impl/AlbumServiceImpl.java
  src/main/java/me/snaptime/common/BaseTimeEntity.java
  src/main/java/me/snaptime/config/RedisConfig.java
  src/main/java/me/snaptime/jwt/redis/RefreshToken.java
  src/main/java/me/snaptime/jwt/redis/RefreshTokenRepository.java
  src/main/java/me/snaptime/profile/service/ProfileService.java
  src/main/java/me/snaptime/profilePhoto/service/ProfilePhotoService.java
  src/main/java/me/snaptime/reply/dto/req/AddChildReplyReqDto.java
  src/main/java/me/snaptime/reply/dto/req/AddParentReplyReqDto.java
  src/main/java/me/snaptime/reply/service/impl/ReplyServiceImpl.java
  src/main/java/me/snaptime/snap/controller/SnapController.java
  src/main/java/me/snaptime/snap/controller/SnapPagingController.java
  src/main/java/me/snaptime/snap/dto/res/FindSnapPagingResDto.java
  src/main/java/me/snaptime/snap/dto/res/SnapDetailInfoDto.java
  src/main/java/me/snaptime/snap/dto/res/SnapInfoDto.java
  src/main/java/me/snaptime/snap/dto/res/SnapPagingResDto.java
  src/main/java/me/snaptime/snap/service/SnapPagingService.java
  src/main/java/me/snaptime/snap/service/SnapService.java
  src/main/java/me/snaptime/snap/service/impl/SnapPagingServiceImpl.java
  src/main/java/me/snaptime/snap/service/impl/SnapServiceImpl.java
  src/main/java/me/snaptime/user/service/SignService.java
  src/main/java/me/snaptime/user/service/UserService.java
  src/main/java/me/snaptime/user/service/impl/SignServiceImpl.java
  src/test/java/me/snaptime/snap/service/SnapPagingServiceImplTest.java
  src/test/java/me/snaptime/social/controller/ReplyControllerTest.java
  src/test/java/me/snaptime/user/service/UserServiceTest.java
Labels: ✨ New Feature

#122 [Feat] 로그인 테스트 기능 구현
  build.gradle
  src/main/java/me/snaptime/config/SecurityConfig.java
  src/main/java/me/snaptime/exception/ExceptionCode.java
  src/main/java/me/snaptime/exception/handler/JwtExceptionHandlerFilter.java
  src/main/java/me/snaptime/jwt/JwtProvider.java
  src/main/java/me/snaptime/user/controller/UserController.java
  src/main/java/me/snaptime/user/dto/res/TestSignInResDto.java
  src/main/java/me/snaptime/user/service/SignService.java
  src/main/java/me/snaptime/user/service/impl/SignServiceImpl.java
Labels: ✨ New Feature
